Fix clang warnings: Use empty array instead of NULL pointer
geany/geany pull request #2889
Opened 2021-09-05 13:05 UTC by rootkea

Hello!

At present, `clang` throws these warnings on master:
```
highlighting.c:1011:3: warning: 'sizeof (((HLKeyword *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                init_styleset_case(CONF);
                ^~~~~~~~~~~~~~~~~~~~~~~~
highlighting.c:966:5: note: expanded from macro 'init_styleset_case'
                                HL_N_ENTRIES(highlighting_keywords_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1014:3: warning: 'sizeof (((HLKeyword *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                init_styleset_case(DIFF);
                ^~~~~~~~~~~~~~~~~~~~~~~~
highlighting.c:966:5: note: expanded from macro 'init_styleset_case'
                                HL_N_ENTRIES(highlighting_keywords_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1032:3: warning: 'sizeof (((HLKeyword *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                init_styleset_case(MAKE);
                ^~~~~~~~~~~~~~~~~~~~~~~~
highlighting.c:966:5: note: expanded from macro 'init_styleset_case'
                                HL_N_ENTRIES(highlighting_keywords_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1034:3: warning: 'sizeof (((HLKeyword *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                init_styleset_case(MARKDOWN);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
highlighting.c:966:5: note: expanded from macro 'init_styleset_case'
                                HL_N_ENTRIES(highlighting_keywords_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1040:3: warning: 'sizeof (((HLKeyword *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                init_styleset_case(PO);
                ^~~~~~~~~~~~~~~~~~~~~~
highlighting.c:966:5: note: expanded from macro 'init_styleset_case'
                                HL_N_ENTRIES(highlighting_keywords_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1050:3: warning: 'sizeof (((HLKeyword *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                init_styleset_case(TXT2TAGS);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
highlighting.c:966:5: note: expanded from macro 'init_styleset_case'
                                HL_N_ENTRIES(highlighting_keywords_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1091:3: warning: 'sizeof (((HLProperty *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                styleset_case(ABAQUS);
                ^~~~~~~~~~~~~~~~~~~~~
highlighting.c:1076:5: note: expanded from macro 'styleset_case'
                                HL_N_ENTRIES(highlighting_properties_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1092:3: warning: 'sizeof (((HLProperty *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                styleset_case(ADA);
                ^~~~~~~~~~~~~~~~~~
highlighting.c:1076:5: note: expanded from macro 'styleset_case'
                                HL_N_ENTRIES(highlighting_properties_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEMENTS(arr)               (sizeof (arr) / sizeof ((arr)[0]))
                                         ~~~~~~~~~~~~ ^
highlighting.c:1093:3: warning: 'sizeof (((HLProperty *)((void *)0)))' will return the size of the pointer, not the array itself [-Wsizeof-pointer-div]
                styleset_case(ASM);
                ^~~~~~~~~~~~~~~~~~
highlighting.c:1076:5: note: expanded from macro 'styleset_case'
                                HL_N_ENTRIES(highlighting_properties_##LANG_NAME)); \
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./highlightingmappings.h:72:48: note: expanded from macro 'HL_N_ENTRIES'
#define HL_N_ENTRIES(array) ((array != NULL) ? G_N_ELEMENTS(array) : 0)
                                               ^~~~~~~~~~~~~~~~~~~
/usr/include/glib-2.0/glib/gmacros.h:820:42: note: expanded from macro 'G_N_ELEMENTS'
#define G_N_ELEME [...]

2021-09-05 21:03 UTC, b4n requested changes
The C standard forbids zero-size arrays.  Yes, [GCC](https://gcc.gnu.org/onlinedocs/gcc/Zero-Length.html) and Clang do allow them as an extension (yet it's not *truly* 0-sized, but basically a VLA), GCC even discourages usage in your use case:
> Declaring zero-length arrays [anywhere but as the last member of a structure], including as interior members of structure objects or as non-member objects, is discouraged

At any rate, it's not valid ISO C, so any compiler would be right to forbid it.  And both GCC and Clang are unhappy about them when passed `-pedantic` (GCC: *error: zero or negative size array ‘foo’*, CLang: *warning: zero size arrays are an extension [-Wzero-length-array]*).

---
It's sad Clang doesn't see that the `NULL` check makes its warning moot, but the fix you propose is not OK as it's not valid C -- and thus likely rejected (rightly) by some compilers (I would guess MSVC might not like it, and maybe some other less common ones).

2021-09-06 09:37 UTC, elextr commented
@rootkea If you are using the same options as [here](https://github.com/geany/geany/issues/2891#issuecomment-913481562), especially -O0 that might explain why the compiler does not notice the protection of the null check.  IIUC compilers need something like -O2 to do the data flow analysis that such checks depend on.  Maybe you could check if you get the warnings with -O2?

2021-09-06 17:38 UTC, rootkea commented
@elextr I still see these warnings with `clang version 10.0.0-4ubuntu1` CFLAGS set to `-Wall -g -O2`.

@b4n I'll look into this tomorrow. :)

2021-09-26 14:16 UTC, rootkea commented
Unfortunately, I couldn't figure out the way to fix these warnings so closing this PR. I just opened #2906 to track these warnings.

2021-09-26 14:16 UTC, closed without merging