Add option to prevent reloading projects that are already loaded
geany/geany pull request #2951
Opened 2021-10-24 00:39 UTC by xiota

This PR adds an option (projects.reload_already_open) to control whether Geany reloads projects that are already loaded.

* The real paths are compared so symlinked files are also caught.
* This affects files opened from both the command line and UI. 
* The default is false, which prevents projects from being reloaded.  Although this is a change from the current behavior:
  - Review of existing plugins indicates minimal, if any, negative effect.
  - The most noticeable difference will be a reduction of warning popups.  Another effect is that undo history will not be lost by an unnecessary reload, which potentially prevents data loss.
  - The option can be enabled by those who really want it.
* When a project is not reloaded, a message is sent to the status window to notify the user.

2021-10-24 01:18 UTC, elextr requested changes
Is this needed? What are the downsides of reloading projects?   Also does reloading a project have useful semantics that this would block, I'm not sure?

If this is desired it should be applied to UI activated opening as well, by doing this in the project open code, not socket code. 

Also technically it should be comparing `realpath`ed absolute filenames so it won't refuse to load projects of the same name in different directories.

2021-10-24 01:18 UTC, elextr commented on src/socket.c
> +			if (!app->project || !(g_strcmp0(app->project->file_name, locale_filename) == 0
Do you need to compare to the locale filename?  IIUC the `project->file_name` has to be UTF-8 or GTK display will be broken, so just compare to UTF-8 filename.

2021-11-07 18:49 UTC, xiota commented
Force push to rebase and combine commits.

2021-11-22 23:49 UTC, xiota commented
Force push to rebase and guarantee no conflicts with recent session-split commit.

2022-04-25 11:37 UTC, closed without merging