Update Lexilla and Scintilla
geany/geany pull request #3292
Opened 2022-09-15 05:20 UTC by data-man

* Lexilla to version 5.19
  * Scintilla to version 5.30
----
Notes:
* sources taken from repositories with important (in my opinion) post-release fixes 
* new Scintilla's features are not used

2022-09-15 06:25 UTC, elextr commented
From a quick look there is a new lexical element SCE_P_ATTRIBUTE which needs to be mapped [here](https://github.com/geany/geany/blob/563d94d856ff5ee799f8c8505681ba4544514c33/src/highlightingmappings.h#L1352).

2022-09-15 20:53 UTC, kugel- commented
> sources taken from repositories with important (in my opinion) post-release fixes

I would rather not add patches not found in the target scintilla release, unless there's a very good reason. If the post-release fixes are important, then lets just wait for 5.3.1

2022-09-15 21:07 UTC, kugel- requested changes

2022-09-15 21:07 UTC, kugel- commented on src/highlightingmappings.h
> +	{ SCE_P_ATTRIBUTE,		"fattribute",		FALSE },
fattribute -> attribute, or is this intention?

2022-09-15 21:07 UTC, kugel- commented on src/highlighting.c
> +				style == SCE_P_ATTRIBUTE);
If I understand the usage in LexPython.cxx correctly then this new style is totally not a string, It seems to refer to Python class attributes, i.e. this is more of an identifier like class members.

2022-10-12 12:38 UTC, data-man commented
Update Lexilla to 5.2.0 and Scintilla to 5.3.1 versions.

Scintilla 5.3.1, released 12 October 2022.
Lexilla 5.2.0, released 12 October 2022.

2022-11-22 01:10 UTC, data-man commented
Closed as unnecessary after two months of ignoring it.

2022-11-22 01:10 UTC, closed without merging

2022-11-22 01:53 UTC, elextr commented
Geany is a volunteer project, nobody is working on it full time.  So just because it hasn't been actioned in some arbitrary time does not mean its unnecessary, just that nobody has had time to review, test and merge yet.