preference option for display size
geany/geany pull request #3365
Opened 2023-01-04 06:36 UTC by 00AR

Implements #3344 
Added a GtkSpinButton in "Notebook tabs" in Interface preferences. This will take as input, number of characters that the user wants to display on the tab label.
For now, Maximum value that can be entered: 100000
**Default value**: 99999(as suggested by @elextr to be very big number)
Minimum value that can be entered: 3
The value is stored in the variable **tab_label_len** declared in GeanyInterfacePrefs struct. This value will be written in **geany.conf** when **save_dialog_prefs** of keyfile.c is executed.
The tab label will get updated dynamically on clicking the Apply/Ok button in the Preferences dialog.
![Screenshot from 2023-01-04 11-34-19](https://user-images.githubusercontent.com/96364226/210493983-dcdc886e-63a0-49b2-b0fd-1a46d3cff13e.png)

2023-01-15 15:15 UTC, eht16 requested changes
Apart from the few comments, it looks very good.

By accident I found https://github.com/geany/geany/issues/2112 which would be solved by this as well.

Maybe you could add "closes #2112 and #3344" to the commit message and rephrase it a bit as "display size" might be confused with the size of the monitor. Maybe something like "Make tab label length configurable".

2023-01-16 00:24 UTC, elextr commented on src/document.c
> +	short_name = document_get_basename_for_display(doc, interface_prefs.tab_label_len);
The window title is usually wider than an individual tab, so using the same setting is not really the best thing.  But at least using the setting would make it variable.

2023-01-16 06:09 UTC, 00AR commented on src/document.c
> +	short_name = document_get_basename_for_display(doc, interface_prefs.tab_label_len);
I wanted to keep the changes minimum and relevant to issue #3344 (my first PR :D) that is why I avoided touching window title. But I will make this change.

2023-01-16 06:43 UTC, 00AR commented
I missed this, does the documentation also needs to be updated?

2023-01-16 07:26 UTC, elextr commented
> does the documentation also needs to be updated?

Yes, just add the description in geany.txt where that dialog is described, @eht16 will add the dialog to his list of images to be updated before release ;-)

2023-01-20 17:35 UTC, eht16 commented
Thanks for the changes, @00AR.

LGTM. I will merge in a few days if there will be no objections.

2023-01-21 10:33 UTC, 00AR commented
> LGTM. I will merge in a few days if there will be no objections.

Alright. Thanks!

2023-01-29 15:44 UTC, merged