Add less and scss file types
geany/geany pull request #3439
Opened 2023-04-01 14:50 UTC by Azq2

This useful for web development.

2024-11-24 10:54 UTC, techee requested changes
About time that LESS and SCSS are finally supported in Geany.

Apart from the several minor comments looks good to me. Would you fix those?

2024-11-24 10:54 UTC, techee commented on data/Makefile.am
> +	filedefs/filetypes.LESS.conf
These are sorted alphabetically in the list in the case-insensitive manner. Could you put them to the right places?

2024-11-24 10:54 UTC, techee commented on data/filetype_extensions.conf
> +Markup=SCSS;LESS;
Drop this line - the [Groups] section is gone now.

2024-11-24 10:54 UTC, techee commented on data/filetype_extensions.conf
> +LESS=*.less;
Despite being related to CSS, it should be sorted alphabetically in the list.

2024-11-24 10:54 UTC, techee commented on data/filedefs/filetypes.LESS.conf
> +mime_type=plain/text
I'd suggest dropping this one if there's no specific mime type. If I remember correctly, the mime type is used for getting the right icon of the file type and better to get the CSS icon here.

2024-11-24 10:54 UTC, techee commented on data/filedefs/filetypes.SCSS.conf
> +mime_type=plain/text
Drop.

2025-01-15 14:12 UTC, closed without merging

2025-01-15 14:28 UTC, Azq2 commented
Sorry, now I use Kate