Skip `tests/test_sidebar` if GTK initialisation fails
geany/geany pull request #3676
Opened 2023-11-05 16:34 UTC by 6t8k

This may happen in headless environments.

The return value of `gtk_init_check` was not examined before; according to [^1], _"calling any GTK function or instantiating any GTK type after this function returns FALSE results in undefined behavior."_

The value 77 can be returned to tell Automake that the test was skipped.[^2][^3]
This should work on Meson too[^4], but I have not tested this here.

---

Based on the example [here](https://www.gnu.org/software/automake/manual/automake.html#Use-TAP-with-the-Automake-test-harness), I assumed that Autotools would mark `test_sidebar` as `SKIP` if all test cases inside are marked as skipped using [`g_test_skip`](https://docs.gtk.org/glib/func.test_skip.html) despite the return value being `0`, but with the way it is plugged together (each binary being one test from the view of the harness without regard for the more granular test cases inside), this doesn't work without further ado:

`test_sidebar.log`:
```
TAP version 13
# random seed: R02Seafe1e22758e0c4a49fe548501665a2d
1..3
# Start of sidebar tests
ok 1 /sidebar/openfiles_none # SKIP Could not initizlize GTK, skipping. Headless environment?
ok 2 /sidebar/openfiles_path # SKIP Could not initizlize GTK, skipping. Headless environment?
ok 3 /sidebar/openfiles_tree # SKIP Could not initizlize GTK, skipping. Headless environment?
# End of sidebar tests
PASS test_sidebar (exit status: 0)
```

`test_sidebar.trs`:
```
:test-result: PASS
:global-test-result: PASS
:recheck: no
:copy-in-global-log: no
```

`geany-2.0/tests $ env TESTS="test_sidebar" make -e check SUBDIRS=`
```
PASS: test_sidebar
============================================================================
Testsuite summary for Geany 2.0
============================================================================
# TOTAL: 1
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

---

However, returning `77`, as proposed here, works as intended:

`test_sidebar.log`:
```
GTK initialisation failed; skipping. Running inside a headless environment?
SKIP test_sidebar (exit status: 77)
```

`test_sidebar.trs`:
```
:test-result: SKIP
:global-test-result: SKIP
:recheck: no
:copy-in-global-log: yes
```

`geany-2.0/tests $ env TESTS="test_sidebar" make -e check SUBDIRS=`
```
SKIP: test_sidebar
============================================================================
Testsuite summary for Geany 2.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  1
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

Fixes #3674

[^1]: https://docs.gtk.org/gtk3/func.init_check.html
[^2]: https://www.gnu.org/software/automake/manual/automake.html#index-Exit-status-77_002c-special-interpretation
[^3]: https://docs.gtk.org/glib/func.test_run.html
[^4]: https://mesonbuild.com/Unit-tests.html#skipped-tests-and-hard-errors

2023-11-06 21:58 UTC, kugel- requested changes

2023-11-06 21:58 UTC, kugel- commented on tests/test_sidebar.c
> +		printf("GTK initialisation failed; skipping. Running inside a headless environment?\n");
Please adapt the above comment to the new code. I'm also unsure if printf output is really desirable during test runs.

2023-12-12 22:37 UTC, b4n requested changes
Looks reasonable, at least better than the finger crossing we had before.

However, skipping the test is clearly not ideal, and using xvfb-run/xwfb-run would probably be better, but might be OK as a future improvement.

2023-12-12 22:37 UTC, b4n commented on tests/test_sidebar.c
> +	}
```suggestion
	if (! gtk_init_check(&argc, &argv))
	{
		g_test_message("GTK initialization failed; skipping. Running inside a headless environment?");
		return 77;
	}
```

2024-01-10 08:57 UTC, zen0bit commented
Trying to build geany for void linux
[PR](https://github.com/void-linux/void-packages/pull/46783)
But test_sidebar also fail for me.

test_sidebar.log:
```
TAP version 13
# random seed: R02S461ac3cd464971e4a48634c6d1556a03
1..3
# Start of sidebar tests
a
b
x
ok 1 /sidebar/openfiles_none
**
Geany:ERROR:test_sidebar.c:69:do_test_sidebar_openfiles: 'g_strv_equal(expected, (const gchar * const *) data)' should be TRUE
~
x
~/b
a
b
not ok /sidebar/openfiles_path - Geany:ERROR:test_sidebar.c:69:do_test_sidebar_openfiles: 'g_strv_equal(expected, (const gchar * const *) data)' should be TRUE
Bail out!
```
Not sure if is same issue, but posting here as related.

Tried to make patches from this and nix packaging, but no luck.

Any suggestions?

PS: Thanks for geany ❤️

2024-01-15 07:29 UTC, zen0bit approved these changes

2024-02-29 00:17 UTC, oreo639 commented
> Sorry, I have no experience with Void Linux ^^; You might get more exposure by posting this as a separate issue. You could still link it to this PR and the accompanying issue.

Just to clarify, Void sets `$HOME` to `/tmp` during the build, which results in gtk evaluating `/tmp` to `~`.
https://github.com/void-linux/void-packages/blob/1c5c95649891f0ffd58e3a368f6b391db219de24/common/xbps-src/shutils/chroot.sh#L99
Setting home to somewhere else during the check (e.g. `$PWD`) does work.

2024-02-29 00:55 UTC, elextr commented
@oreo639 this is a pull request that fixes an issue with a single test, it is not an issue, please do not hijack it.  As suggested above please raise a separate issue

2024-02-29 00:57 UTC, oreo639 commented
I'm explaining that it isn't an issue, sorry.

2025-08-13 22:04 UTC, closed without merging