Correction of issue #3678
geany/geany pull request #3681
Opened 2023-11-11 01:40 UTC by BayashiPascal

Correction of issue #3678 (Symbol list does not get the focus when access through key binding)

2023-11-12 11:58 UTC, ntrel commented
One issue with this is that it always focuses the treeview. If the entry was focused, it will change the focus to the treeview. I think the entry may be more useful, because even if the treeview focus is wanted, the user can just press the down key. To do that, this lookup works:
```
		gtk_widget_grab_focus(ui_lookup_widget(main_widgets.window, "entry_tagfilter"));
```

2023-11-12 22:59 UTC, elextr commented
Or the normal tab/shift tab navigation can go between entry and tree (and back).

2023-11-12 23:41 UTC, BayashiPascal commented
I confirm that 
```
gtk_widget_grab_focus(ui_lookup_widget(main_widgets.window, "entry_tagfilter"));
```
works for me, and I too really don't understand why the same call on `treeview2` (the initial correction I suggested) doesn't work...

About focusing the tree or the entry, there is something I don't quite understand here: what's the point of the new entry ? I was used to a version of Geany without the entry widget. After focusing the tree, if I input something it automatically opens an entry widget at the bottom of the tree, which seems to work exactly as the new entry, and which still exists in the new version. Hence, to me, the new entry widget only waste one line that could be used for the tree, and require one more action (arrow or tab) to do something that could, and still can, be done without using it.

2023-11-13 00:18 UTC, elextr commented
The new entry is a filter, it reduces the tree to matching elements, the one that pops up when you type on the tree is a search, it changes the selected element to the first match.

2023-11-13 00:32 UTC, BayashiPascal commented
Oh, I've just noticed the difference between the two ! Sorry for my previous comment and thanks for the clarification. That's a nice feature addition indeed.

I'm so use to the search mode only that I think I would prefer to keep the tree focused, but I would understand that someone else think the other way, in which case the correction suggested by @ntrel  is surely better than mine (shorter and more readable).

2023-11-13 00:49 UTC, elextr commented
Using the name is in theory more robust to further layout changes, but "treeview2" should be too, but isn't.  I have no preference so will referee any duel between users that eventuates ;-)

2023-11-17 23:07 UTC, b4n commented
I don't really care either for which it is; but maybe restoring this to the previous state is the safer solution.
FWIW, I don't use that shortcut (didn't even know it existed :smile:) so I don't mind.

> works for me, and I too really don't understand why the same call on `treeview2` (the initial correction I suggested) doesn't work...

This is more subtle :)  The reason is that the actual `GtkTreeView` is either the default empty one, or the *document's* one.  So the one in Glade (retrieved with the `treeview2` name) is likely not the one actually attached to the symbols tab.
The correct fix is:

```diff
diff --git a/src/sidebar.c b/src/sidebar.c
index 9d004f392..435e31394 100644
--- a/src/sidebar.c
+++ b/src/sidebar.c
@@ -1649,7 +1649,7 @@ void sidebar_focus_symbols_tab(void)
 	if (ui_prefs.sidebar_visible && interface_prefs.sidebar_symbol_visible)
 	{
 		GtkNotebook *notebook = GTK_NOTEBOOK(main_widgets.sidebar_notebook);
-		GtkWidget *symbol_list_scrollwin = gtk_notebook_get_nth_page(notebook, TREEVIEW_SYMBOL);
+		GtkWidget *symbol_list_scrollwin = ui_lookup_widget(main_widgets.window, "scrolledwindow2");
 
 		gtk_notebook_set_current_page(notebook, TREEVIEW_SYMBOL);
 		gtk_widget_grab_focus(gtk_bin_get_child(GTK_BIN(symbol_list_scrollwin)));
```

2023-11-17 23:09 UTC, b4n requested changes
This is way too specific and fragile.  Do this instead:

```diff
diff --git a/src/sidebar.c b/src/sidebar.c
index 9d004f392..435e31394 100644
--- a/src/sidebar.c
+++ b/src/sidebar.c
@@ -1649,7 +1649,7 @@ void sidebar_focus_symbols_tab(void)
 	if (ui_prefs.sidebar_visible && interface_prefs.sidebar_symbol_visible)
 	{
 		GtkNotebook *notebook = GTK_NOTEBOOK(main_widgets.sidebar_notebook);
-		GtkWidget *symbol_list_scrollwin = gtk_notebook_get_nth_page(notebook, TREEVIEW_SYMBOL);
+		GtkWidget *symbol_list_scrollwin = ui_lookup_widget(main_widgets.window, "scrolledwindow2");
 
 		gtk_notebook_set_current_page(notebook, TREEVIEW_SYMBOL);
 		gtk_widget_grab_focus(gtk_bin_get_child(GTK_BIN(symbol_list_scrollwin)));
```

2023-11-18 01:22 UTC, BayashiPascal commented
I've tested @b4n correction and it works for me. I agree that using `scrolledwindow2` is a better way of correcting the problem, so I've modified the PR accordingly.

2023-11-19 23:56 UTC, b4n requested changes
LGTM (obviously) but for the tiny style issue.

2023-11-19 23:56 UTC, b4n commented on src/sidebar.c
> +		GtkWidget *symbol_list_scrollwin = ui_lookup_widget(main_widgets.window, "scrolledwindow2");
Please keep the blank line between the variable declaration block and the rest (yes, it's kind of the same here, but that's currently how we do things everywhere else)

```suggestion
		GtkWidget *symbol_list_scrollwin = ui_lookup_widget(main_widgets.window, "scrolledwindow2");

```

2023-12-09 23:07 UTC, b4n approved these changes
LGTM

2023-12-09 23:23 UTC, merged

2023-12-09 23:24 UTC, b4n commented
@ntrel @elextr I'm merging this, as if fixes a clear bug and restores the previous behavior.  If you'd like to focus the search field instead (which indeed might make sense, but I don't have a strong opinion yet), feel free to open a follow-up.

2023-12-09 23:25 UTC, b4n commented
@BayashiPascal I squashed the commits together and adjusted the commit message to make it clearer.  Thanks for the patch! :+1:

2023-12-10 01:34 UTC, BayashiPascal commented
@b4n You're welcome. I'm glad to have been able to contribute and hope I can do it again in the future.

2023-12-10 01:49 UTC, elextr commented
> If you'd like to focus the search field instead (which indeed might make sense, but I don't have a strong opinion yet)

Nah, I use the moose, so I can click on what I want.